data = [
  {'name': 'Cristiano Ronaldo', 'follower_count': 630, 'description': 'Footballer', 'country': 'Portugal'},
  {'name': 'Lionel Messi', 'follower_count': 520, 'description': 'Footballer', 'country': 'Argentina'},
  {'name': 'Selena Gomez', 'follower_count': 429, 'description': 'Musician and actress', 'country': 'United States'},
  {'name': 'Kylie Jenner', 'follower_count': 400, 'description': 'Reality TV star', 'country': 'United States'},
  {'name': 'Dwayne Johnson', 'follower_count': 396, 'description': 'Actor and wrestler', 'country': 'United States'},
  {'name': 'Ariana Grande', 'follower_count': 380, 'description': 'Musician and actress', 'country': 'United States'},
  {'name': 'Kim Kardashian', 'follower_count': 360, 'description': 'TV personality', 'country': 'United States'},
  {'name': 'Beyoncé', 'follower_count': 320, 'description': 'Musician', 'country': 'United States'},
  {'name': 'Khloé Kardashian', 'follower_count': 310, 'description': 'TV personality', 'country': 'United States'},
  {'name': 'Nike', 'follower_count': 290, 'description': 'Sports brand', 'country': 'United States'},
  {'name': 'Kendall Jenner', 'follower_count': 280, 'description': 'Model', 'country': 'United States'},
  {'name': 'Justin Bieber', 'follower_count': 270, 'description': 'Musician', 'country': 'Canada'},
  {'name': 'Taylor Swift', 'follower_count': 260, 'description': 'Singer-songwriter', 'country': 'United States'},
  {'name': 'Virat Kohli', 'follower_count': 260, 'description': 'Cricketer', 'country': 'India'},
  {'name': 'Jennifer Lopez', 'follower_count': 250, 'description': 'Singer and actress', 'country': 'United States'},
  {'name': 'Nicki Minaj', 'follower_count': 240, 'description': 'Rapper', 'country': 'United States'},
  {'name': 'Kourtney Kardashian', 'follower_count': 220, 'description': 'TV personality', 'country': 'United States'},
  {'name': 'Miley Cyrus', 'follower_count': 215, 'description': 'Musician and actress', 'country': 'United States'},
  {'name': 'Rihanna', 'follower_count': 210, 'description': 'Musician and entrepreneur', 'country': 'Barbados'},
  {'name': 'Zendaya', 'follower_count': 200, 'description': 'Actress', 'country': 'United States'},
  {'name': 'Shakira', 'follower_count': 190, 'description': 'Musician', 'country': 'Colombia'},
  {'name': 'Billie Eilish', 'follower_count': 180, 'description': 'Singer-songwriter', 'country': 'United States'},
  {'name': 'Neymar', 'follower_count': 179, 'description': 'Footballer', 'country': 'Brazil'},
  {'name': 'Bad Bunny', 'follower_count': 170, 'description': 'Musician', 'country': 'Puerto Rico'},
  {'name': 'Chris Hemsworth', 'follower_count': 150, 'description': 'Actor', 'country': 'Australia'}
]
